name: Merge PR
on:
  pull_request:
    types:
      - closed
    branches:
      - main
concurrency:
  group: merge
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: aarch64-darwin
            runner: depot-macos-15 # Depot Apple Silicon M2, 8 CPUs, 24 GB RAM, 400 GB SSD
            build_command: nix build -L .#binary-gnosis_vpn-update-aarch64-darwin
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # build-binaries-v3
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      version_type: pr
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: gnosis-vpn-toolkit
      build_command: ${{ matrix.build_command }}
      binary: gnosis_vpn-update
      runner: ${{ matrix.runner }}
      timeout_minutes: 240
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY }}
      gpg_private_key_password: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY_PASSWORD }}
      apple_certificate: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 }}
      apple_certificate_password: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_PASSWORD }}
