name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
concurrency:
  group: ${{ github.ref }}-pr
  cancel-in-progress: true
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: aarch64-darwin
            runner: depot-macos-15 # Depot Apple Silicon M2, 8 CPUs, 24 GB RAM, 400 GB SSD
            build_command: nix build -L .#binary-gnosis_vpn-update-aarch64-darwin
            build_debug_command: nix build -L .#binary-gnosis_vpn-update-aarch64-darwin-dev
            required_label: ""
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # build-binaries-v3
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      # NOTE: this Cachix cache must be created for the gnosis_vpn-toolkit repo.
      cachix_cache_name: gnosis-vpn-toolkit
      build_command: ${{ matrix.build_command }}
      build_debug_command: ${{ matrix.build_debug_command }}
      binary: gnosis_vpn-toolkit
      gcp_workload_identity_provider: projects/656686060169/locations/global/workloadIdentityPools/gnosisvpn-gh-pool/providers/github-provider
      gcp_service_account: download-gnosisvpn-gh-sa@gnosisvpn-production.iam.gserviceaccount.com
      runner: ${{ matrix.runner }}
      timeout_minutes: 240
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label) }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY }}
      gpg_private_key_password: ${{ secrets.GNOSISVPN_GPG_PRIVATE_KEY_PASSWORD }}
      apple_certificate: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_P12_BASE64 }}
      apple_certificate_password: ${{ secrets.APPLE_CERTIFICATE_DEVELOPER_PASSWORD }}
  checks:
    name: Checks
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: depot-macos-15
    steps:
      - name: Run checks
        uses: hoprnet/hopr-workflows/actions/nix-action@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_cache_name: gnosis-vpn-toolkit
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          command: nix flake check -L --show-trace --max-jobs 1
